//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergoControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counter
    {
        public short IDCounter { get; set; }
        public short Current { get; set; }
        public short Voltage { get; set; }
        public short CosFi { get; set; }
    }
}
